image: mcasimir/dind-node-build-runner:6.2.1

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - xvfb-run npm run test:ci
  except:
    - tags
  tags:
    - docker
    - node
